//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woolpert.BusinessObjects.Accela
{
    using System;
    using System.Collections.Generic;
    
    public partial class B1PERMIT
    {
        public string SERV_PROV_CODE { get; set; }
        public string B1_PER_ID1 { get; set; }
        public string B1_PER_ID2 { get; set; }
        public string B1_PER_ID3 { get; set; }
        public string B1_REF_ID1 { get; set; }
        public string B1_REF_ID2 { get; set; }
        public string B1_REF_ID3 { get; set; }
        public string B1_PER_GROUP { get; set; }
        public string B1_PER_TYPE { get; set; }
        public string B1_PER_SUB_TYPE { get; set; }
        public string B1_PER_CATEGORY { get; set; }
        public string R3_STD_TIME_CLASS_CODE { get; set; }
        public Nullable<System.DateTime> B1_FILE_DD { get; set; }
        public string B1_SPECIAL_TEXT { get; set; }
        public string B1_Q_UD1 { get; set; }
        public string B1_Q_UD2 { get; set; }
        public string B1_Q_UD3 { get; set; }
        public string B1_Q_UD4 { get; set; }
        public Nullable<decimal> B1_STANDARD_TIME { get; set; }
        public string B1_EVENT_CODE { get; set; }
        public System.DateTime REC_DATE { get; set; }
        public string REC_FUL_NAM { get; set; }
        public string REC_STATUS { get; set; }
        public Nullable<long> PROJECT_NBR { get; set; }
        public string B1_REF_ID { get; set; }
        public string B1_ALT_ID { get; set; }
        public Nullable<long> B1_TRACKING_NBR { get; set; }
        public string B1_APPL_STATUS { get; set; }
        public string APP_STATUS_GROUP_CODE { get; set; }
        public Nullable<System.DateTime> B1_APPL_STATUS_DATE { get; set; }
        public string B1_MODULE_NAME { get; set; }
        public Nullable<System.DateTime> B1_REPORTED_DATE { get; set; }
        public string B1_CREATED_BY_ACA { get; set; }
        public string B1_APPL_CLASS { get; set; }
        public string B1_APP_TYPE_ALIAS { get; set; }
        public string B1_CREATED_BY { get; set; }
        public string B1_ACCESS_BY_ACA { get; set; }
        public string B1_INITIATED_BY_PRODUCT { get; set; }
        public string B1_IS_MANUAL_ALT_ID { get; set; }
        public string B1_DELEGATE_USER_ID { get; set; }
        public string B1_PAYMENT_STATUS { get; set; }
        public string B1_CERTIFICATION_APPLIED { get; set; }
        public Nullable<System.DateTime> B1_CERTIFICATION_DATE { get; set; }
        public string B1_PENDING_VALIDATION { get; set; }
    }
}
